# Generated by Django 5.0 on 2024-03-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='name',
            new_name='neighborhood_name',
        ),
    ]
