# Generated by Django 5.0 on 2024-03-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_rename_name_neighborhood_neighborhood_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='consultory_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='dayweek',
            old_name='name',
            new_name='day_week_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
    ]
